name: Bug report
description: Report a reproducible problem in spark-fuse
title: "[Bug]: "
labels: [bug]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-checks
      options:
        - label: I searched existing issues and discussions
          required: true
        - label: I can reproduce this with the latest release
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
      placeholder: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Provide minimal, complete steps or code to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
        ```python
        # minimal code snippet
        ```
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/traceback
      description: Paste relevant logs or stack traces.
      render: text
  - type: input
    id: spark_fuse_version
    attributes:
      label: spark-fuse version
      placeholder: e.g., 0.1.5
    validations:
      required: true
  - type: input
    id: python_version
    attributes:
      label: Python version
      placeholder: e.g., 3.11.7
  - type: input
    id: spark_version
    attributes:
      label: Spark version
      placeholder: e.g., 3.4.2
  - type: input
    id: delta_version
    attributes:
      label: delta-spark version
      placeholder: e.g., 3.2.0
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 14 / Ubuntu 22.04 / Windows 11
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      multiple: true
      options:
        - Local
        - Databricks
        - Microsoft Fabric
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Links, screenshots, or anything else helpful.
