name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build distributions
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Validate distributions
        run: |
          python -m pip install --upgrade twine
          python -m twine check dist/*
      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
